extends: airbnb-base
plugins:
- import
- jest
rules:
  no-console: 0
  arrow-parens: 0
  camelcase: 0
  no-plusplus: 0
  prefer-const: 0
  no-param-reassign: 0
  prefer-promise-reject-errors: 0
  import/no-cycle: 0
  jest/no-disabled-tests: "warn"
  jest/no-focused-tests: "error"
  jest/no-identical-title: "error"
  jest/prefer-to-have-length: "warn"
  jest/valid-expect: 'error'
