/* eslint-disable import/prefer-default-export */
import { mirrorKeyArray } from '../utils';

// import { OAUTH_SCOPES } from '../src/constants';

export const OAUTH_SCOPES = Object.freeze(mirrorKeyArray([
  'identify',
  'email',
  'connections',
  'guilds',
  'guilds.join',
  'gdm.join',
  'rpc',
  'rpc.notifications.read',
  'rpc.voice.read',
  'rpc.voice.write',
  'rpc.activities.write',
  'bot',
  'webhook.incoming',
  'messages.read',
  'applications.builds.upload',
  'applications.builds.read',
  'applications.commands',
  'applications.store.update',
  'applications.entitlements',
  'activities.read',
  'activities.write',
  'relationships.read',
]));

export const ROLE_PERMISSIONS = Object.freeze(mirrorKeyArray([
  'ADMINISTRATOR',
  'CREATE_INSTANT_INVITE',
  'KICK_MEMBERS',
  'BAN_MEMBERS',
  'MANAGE_CHANNELS',
  'MANAGE_GUILD',
  'ADD_REACTIONS',
  'VIEW_AUDIT_LOG',
  'PRIORITY_SPEAKER',
  'STREAM',
  'VIEW_CHANNEL',
  'SEND_MESSAGES',
  'SEND_TTS_MESSAGES',
  'MANAGE_MESSAGES',
  'EMBED_LINKS',
  'ATTACH_FILES',
  'READ_MESSAGE_HISTORY',
  'MENTION_EVERYONE',
  'USE_EXTERNAL_EMOJIS',
  'VIEW_GUILD_INSIGHTS',
  'CONNECT',
  'SPEAK',
  'MUTE_MEMBERS',
  'DEAFEN_MEMBERS',
  'MOVE_MEMBERS',
  'USE_VAD',
  'CHANGE_NICKNAME',
  'MANAGE_NICKNAMES',
  'MANAGE_ROLES',
  'MANAGE_WEBHOOKS',
  'MANAGE_EMOJIS',
]));
